# my_set = set([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 3, 3, 33])
# print(my_set)
# my_set = {1, 2, 3, 4}
# print(my_set)

# # Adding an element to a set
# my_set = {1, 2, 3} 
# my_set.add(4)
# print(my_set)

# my_set = {1, 2, 3, 4}
# my_set.remove(3)
# print(my_set)
# my_set = {1, 2, 3, 4}
# my_set.discard(2)
# print(my_set)


# set1 = {1, 2, 3}
# set2 = {4, 5, 6}
# union_set = set1.union(set2)
# print(union_set)

#     ##  or  ##

# union_set = set1 | set2


# set1 = {1, 2, 3}
# set2 = {3, 4, 5}
# intersection_set = set1.intersection(set2)
# print(intersection_set)

#     ##  or  ##

# set1 = {1, 2, 3}
# set2 = {3, 4, 5}
# intersection_set = set1 & set2
# print(intersection_set)


# set1 = {1, 2, 3}
# set2 = {3, 4, 5}
# difference_set = set1.difference(set2)
# print(difference_set)


# set1 = {1, 2, 3}
# set2 = {3, 4, 5}
# sym_diff_set = set1.symmetric_difference(set2)  # sym_diff_set is {1, 2, 4, 5}
# print(sym_diff_set)

# my_set = {1, 2, 3}
# print(2 in my_set)  # Output: False
# print(4 in my_set)  # Output: True

    ##  or  ##

# my_set = {1, 2, 3}
# for item in my_set:
#     print(item)

















































